version: '3.8'

services:
  open-adventure:
    build:
      context: .
      dockerfile: Dockerfile.ci
    volumes:
      - .:/app
    working_dir: /app
    command: ["/bin/sh", "-c", "make && ./advent"]
